// Auto-generated by scripts/build-content.mjs — do not edit directly.
window.WORKFLOW_FSM_DATA = {
  "id": "piDirectorWorkflow",
  "version": "2.6.11",
  "title": "Pi Director Agent Workflow",
  "summary": "7-E Compound Lifecycle across user-owned modes: ALIGN (envision entry, evaluate primary, establish secondary), SPEC (explore primary, elaborate secondary), VIBE (execute primary, examine secondary). New interactive sessions and handoffs start at envision in ALIGN. Each mode has a primary home for active execution/self-loops and a secondary gate to capture/verify and CALL next. Runtime owns native UI, session identity, timing, persistence mechanics, and mode markers. Agent owns judgment, artifact meaning, scope, decisions, and final output.",
  "session": {
    "mode": "latest persisted User choice (align | spec | vibe); new and handed-off interactive sessions start in ALIGN",
    "artifact": "one versioned .pi/plan/<name>.md continued across modes and handoffs",
    "scope": "initial Goal + accepted follow-ups + every unresolved Checklist (C) outcome",
    "review": "unresolved Agent decisions (D) that still need explicit User acceptance in ALIGN"
  },
  "ownership": [
    "Mode belongs to the User: latest persisted choice wins; new and handed-off interactive sessions start in ALIGN.",
    "The /mode command is the universal manual bypass to open the option picker and choose what to do next.",
    "Manual /mode bypass transitions are User-owned escape hatches — never gated on workflow completeness or unresolved D reviews.",
    "CALL means invoke ask, decide, start, or next; READ, EDIT, APPEND, and RETURN are Agent-owned actions.",
    "Project-write boundaries are Agent rules, not a runtime filesystem guard.",
    "A genuinely unrelated goal requires a fresh session; NEVER delete plan artifacts automatically.",
    "NEVER advance the hidden memory-review marker outside /init.",
    "NEVER create or edit .pi/plan/* until start writes the named artifact.",
    "NEVER CALL decide or next before start writes the named artifact. Envision entry MAY CALL ask before start when no named artifact exists."
  ],
  "invariants": [
    "ONLY VIBE MAY change files outside .pi; ALIGN and SPEC update .pi workflow state only.",
    "ALIGN may NEVER search or read extensions/, deep docs/, or other source — Spec explore owns research; Vibe may read what implementation needs. Envision before the first scope ask: no extra file reads — use the kickoff plus harness-injected AGENTS.md already in context. After that ask and start, Align may read the session plan, then `.pi/AGENTS.md` and `.pi/MEMORY.md` as needed. NEVER list `.pi/plan/` or read sibling plans, root README.md, or package.json just to unlock start.",
    "One versioned .pi/plan/<name>.md continues across modes and handoffs.",
    "Retain Digest, Goal, Align, Decisions, Evidence, Proposal, Checklist, Work log, User transcript, and Agent transcript.",
    "Work log, User transcript, and Agent transcript are append-only.",
    "Checklist is cumulative; latest explicit state wins without hiding earlier lifecycle context.",
    "Assign every question, Agent decision, and checklist outcome one stable Agent-chosen slug (`Q-goal-scope`, `D-tighten-writes`, `C-diagnose-jobs`); NEVER reuse or rename. User and Agent see the same slug. NEVER embed those ids in option labels.",
    "KEEP **Current work:** as the Progress Tracker working-row phrase: one short in-flight C or D line while a run is in flight, or empty while waiting on User.",
    "NEVER copy Checklist, HTML comments, or format markers into Current work and NEVER add a todo tool.",
    "KEEP ## Digest as two short bullets Current (where we are) and Desired (where this task goes). Show plan displays only Digest. Rewrite Digest when direction changes; do not append history there.",
    "KEEP the artifact resumable without relying on chat history after every turn.",
    "Runtime does not parse artifact prose (only time-spent envelope, Current work line, and ## Digest for Show plan).",
    "ONLY secondary gates (establish, elaborate, examine) may CALL next; primaries never CALL next.",
    "NEVER recommend the current persisted mode in next actions; same-mode stay is ESC, Return to editor, or /mode."
  ],
  "always": [
    "SIZE process and output to the work.",
    "LEAD with the result and NAME paths, symbols, evidence, and unresolved choices instead of restating files.",
    "DO NOT repeat transcript or artifact prose in the final response.",
    "NEVER claim a mutation, decision, check, or acceptance that did not occur.",
    "NEVER silently remove an initial goal, accepted outcome, unresolved C item, or unresolved D review."
  ],
  "turn": [
    "RUN CAPTURE_TURN(message).",
    "IF message adds, conflicts with, or appears to replace scope THEN RUN RECONCILE_SCOPE(message); IF unresolved THEN RETURN.",
    "RUN the modeBodies entry for the persisted User mode (align | spec | vibe)."
  ],
  "modeBodies": [
    {
      "mode": "align",
      "label": "ALIGN",
      "states": [
        "envision",
        "evaluate",
        "establish"
      ],
      "primary": "evaluate",
      "secondary": "establish",
      "steps": [
        "IF session entry (new interactive session, handoff continue, or envision not yet run): RUN envision once — no extra file reads, CALL ask once for goal-scope (one CALL, batch independent questions; before start when no named artifact); on answered CALL start with a scope-informed name then evaluate; on cancel do not start.",
        "IF envision Ask routes directly to SPEC or VIBE THEN settle into that mode's primary (explore or execute); on cancel RETURN without evaluate.",
        "AFTER envision scope is answered (not routed) and start/reuse has named the artifact: PROCEED to evaluate.",
        "RUN evaluate (primary home): check artifact for unresolved D review, Checklist gaps, residuals; CALL ask for D-review, User-requested clarification, RECONCILE_SCOPE, or follow-ups — do not re-fish entry scope already captured in envision; NEVER CALL next from evaluate; NEVER explore the codebase in Align.",
        "IF evaluate Ask routes directly to SPEC or VIBE THEN settle into that mode's primary (explore or execute).",
        "WHEN ready to leave Align or to confirm routing after ask: RUN establish (secondary gate).",
        "establish: confirm/summarize only — NEVER CALL ask; either RETURN to evaluate (more primary/ask work) or CALL next with other modes + handoff only (never align). Agent-driven Align never ends a turn with neither ask nor next.",
        "Same-mode stay: do not CALL next with align; User uses ESC/Return or /mode.",
        "Align reads: before the first scope ask, harness-injected AGENTS.md only (no extra file reads); after that ask and start, the session plan then `.pi` as needed — all codebase exploration is Spec (or Vibe when implementing)."
      ]
    },
    {
      "mode": "spec",
      "label": "SPEC",
      "states": [
        "explore",
        "elaborate"
      ],
      "primary": "explore",
      "secondary": "elaborate",
      "steps": [
        "Land on and RUN explore (primary): bounded research into Evidence; decide for material autonomous choices when needed.",
        "WHEN ready to propose or route: RUN elaborate (secondary).",
        "elaborate: confirm/summarize — draft Proposal/Checklist, RECORD_DECISION as needed, RUN CLOSE_OUT, then either RETURN to explore (more research) or CALL next with other modes only (never spec). Do not recommend Align landing establish idle — static Return→ALIGN covers editor standby. Only when unresolved D ids exist: Align landing evaluate (landing:\"evaluate\", prompt includes a standalone D-topic slug such as D-tighten-writes, auto-start ask)."
      ]
    },
    {
      "mode": "vibe",
      "label": "VIBE",
      "states": [
        "execute",
        "examine"
      ],
      "primary": "execute",
      "secondary": "examine",
      "steps": [
        "Land on and RUN execute (primary): implement accepted scope; decide for material autonomous choices when needed.",
        "WHEN ready to verify or route: RUN examine (secondary).",
        "examine: confirm/summarize — run checks, RECORD evidence, RUN CLOSE_OUT, then either RETURN to execute (more implementation) or CALL next with other modes only (never vibe). Do not recommend Align landing establish idle — static Return→ALIGN covers editor standby. Only when unresolved D ids exist: Align landing evaluate with a standalone D-topic slug (D-tighten-writes) in prompt (auto-start ask)."
      ]
    }
  ],
  "procedures": {
    "CAPTURE_TURN": [
      "IF message is workflow-generated or a command THEN RETURN.",
      "Redact credentials, secret values, and attachment bodies.",
      "IF no named artifact exists OR the first envision scope ask has not completed THEN RETAIN captured message in session only; do not CREATE or EDIT .pi/plan/* until start.",
      "ELSE APPEND captured message verbatim to User transcript before substantive work.",
      "RUN WRITE_ARTIFACT when the artifact exists AND the retain-before-first-ask rule does not apply."
    ],
    "RECONCILE_SCOPE": [
      "COMPARE message with Goal, accepted follow-ups, and every unresolved C outcome.",
      "IF unambiguous and additive THEN APPEND a stable C outcome without deleting or renaming earlier outcomes; RETURN resolved.",
      "IF mode = ALIGN THEN CALL ask from evaluate with concrete keep/defer/replace/resolve options; on cancel RETURN unresolved; else APPEND full exchange to User transcript; RECORD synthesis in Goal, Align, Decisions, Checklist; ANNOTATE superseded/deferred/skipped/failed C with reasons; NEVER erase; RETURN resolved.",
      "IF mode = SPEC or VIBE THEN CALL decide with the same option shape; ACCEPT highest-confidence pick as working choice; ANNOTATE C and leave D review unresolved; RETURN resolved."
    ],
    "WRITE_ARTIFACT": [
      "IF no named artifact exists THEN RETURN success without creating .pi/plan/*.",
      "INCLUDE **Current work:** when the in-flight outcome starts or changes so the Progress Tracker working row can paint this run.",
      "KEEP ## Digest Current / Desired current when direction changes.",
      "TRY EDIT or APPEND; IF fail THEN RETRY once.",
      "IF retry fails THEN WARN concisely and CONTINUE only when still safely resumable; IF HANDOFF requires the change THEN RETURN failure."
    ],
    "RECORD_DECISION": [
      "IF choice is NOT (material AND reversible AND autonomous AND in scope) AND does not cross a consequential or safety boundary THEN RETURN.",
      "CALL decide with the question, context, and 2-3 viable compared options.",
      "TREAT the returned pick as the working choice with review state unresolved.",
      "DO NOT assign a second D identifier for that decide call.",
      "DO NOT add the choice to Decisions until explicit User acceptance in ALIGN.",
      "ALLOW implementation, verification, and CLOSE_OUT to update lifecycle but NEVER imply User approval."
    ],
    "BLOCKED": [
      "STOP affected work without improvising or widening scope.",
      "RECORD reason, evidence, viable options, recommendation, and affected C/D identifiers.",
      "IF a decide-shaped choice remains THEN CALL decide and CONTINUE only when that pick unblocks the work.",
      "RECORD broader ALIGN review as the recommended continuation.",
      "RUN CLOSE_OUT.",
      "RETURN unresolved."
    ],
    "CLOSE_OUT": [
      "APPEND phase result, actual changed paths, checks run, checks not run, limitations, and concerns to Work log.",
      "RECONCILE initial Goal, accepted follow-ups, every C outcome, and every D lifecycle from the artifact as a whole.",
      "FOR EACH C outcome: MARK completed only with evidence; OTHERWISE keep unresolved, or annotate deferred/skipped/failed with a reason.",
      "NEVER present the task as complete while an accepted outcome remains unresolved.",
      "NEVER mark a D User-approved without an explicit review answer.",
      "PROMOTE only durable orientation or costly quirks to project memory; NEVER advance the hidden memory-review marker.",
      "IF actionable work remains THEN CALL next from the current secondary gate with ranked other modes and handoff only — NEVER include the current persisted mode.",
      "Align dual landing: do not emit agent Align landing \"establish\" idle rows — static Return→ALIGN (and Return to editor) cover editor standby. Only if unresolved D items need acceptance: align action with landing \"evaluate\", prompt that includes a standalone D-topic slug (D-tighten-writes), auto-start ask — do not invent extra questions. Runtime drops redundant establish recommendations if emitted.",
      "next reason MUST be a short user-facing slug in plain English (what the User gets); plan slugs (Q-topic/C-topic/D-topic) only as optional trailing [] or (); never bare codes as the whole reason. Runtime rejects a blank/whitespace-only reason. Spec/Vibe still need contextual prompt; Align evaluate needs a standalone D-topic slug (D-tighten-writes); handoff omits prompt. Runtime prepends Switch context only when auto-starting.",
      "ELSE IF more work remains in the current mode THEN RETURN to the mode primary (do not CALL next with the current mode).",
      "ELSE IF persisted mode is align THEN CALL next from establish with other modes and handoff only (never align); never idle an agent-driven Align turn without ask or next. Runtime NEXT_ALIGN establish landing is not an agent turn.",
      "ELSE DO NOT CALL next.",
      "ENSURE artifact is resumable and final output is truthful and concise."
    ],
    "HANDOFF": [
      "IF no named artifact exists THEN DO NOT invent a temporary plan; RETURN without handing off.",
      "IF artifact is current format THEN USE the already-written artifact; DO NOT start a checkpoint turn; KEEP leftover current-format files as-is.",
      "ELSE DO NOT mutate the legacy artifact.",
      "CONTINUE in fresh ALIGN with the ordinary continue line (envision: artifact ready → one ask call → evaluate).",
      "READ the whole current artifact or immutable legacy reference.",
      "Envision still CALL ask once about goal scope ahead after reusing the artifact (one CALL, batch independent questions); choose the most important unresolved scope item for that question."
    ],
    "LEGACY_CONTINUATION": [
      "ACCEPT persisted legacy modes as readable; /questionnaire does not exist.",
      "NEVER mutate an artifact without the current format marker.",
      "CALL start before the first .pi write to create a linked current-format continuation.",
      "LET runtime carry recognized historical timing into the continuation.",
      "CONVERT meaningful legacy goal, evidence, decisions, and checklist history into flat sections.",
      "PRESERVE the legacy file unchanged.",
      "CALL ask only when the meaning or desired carry-forward is genuinely uncertain."
    ]
  },
  "states": {
    "envision": {
      "id": "envision",
      "label": "ENVISION",
      "kind": "guided",
      "userMode": "align",
      "role": "entry",
      "summary": "Session entry only: capture goal, no extra file reads, CALL ask once about goal scope ahead (one CALL, batch independent questions), then start/reuse the named artifact before evaluate.",
      "permission": "read",
      "substates": [
        "goalCapture",
        "scopeAsk",
        "ensureArtifact"
      ],
      "procedure": [
        "Run once per new interactive session or handoff continue — not a repeating Align loop peer.",
        "Capture user goal and intent when present.",
        "Do not READ extra files before the first scope ask: use the kickoff plus harness-injected AGENTS.md already in context. NEVER re-read AGENTS.md, NEVER read `.pi/AGENTS.md`, `.pi/MEMORY.md`, `.pi/plan/`, sibling plans, root README.md, package.json, or source to unlock start.",
        "IF a named artifact already exists THEN reuse it (handoff continue). ELSE do not CALL start yet.",
        "CALL ask with at least one independent question about goal scope ahead (outcomes, constraints, boundaries). Envision entry MAY CALL ask before start when no named artifact exists.",
        "On ask cancel: RETURN without evaluate, without start, and without calling next; do not invent scope.",
        "AFTER the first scope ask is answered (not routed): IF no named artifact exists THEN CALL start exactly once with a scope-informed 2–4 word name; the first write includes initial goal and settled scope. ELSE keep the existing named artifact.",
        "APPEND every completed prompt, context, displayed option, confidence, and exact answer to User transcript.",
        "SYNTHESIZE into Goal, Align, Decisions, and Checklist after start (or into the reused artifact).",
        "Do not CALL ask again from envision; dependent follow-ups run in evaluate after ARTIFACT.",
        "IF Ask routes directly to SPEC or VIBE THEN: if no named artifact, the target CALL start first then synthesize; proceed to EXPLORE or EXECUTE (skip evaluate).",
        "WHEN the envision ask is answered and not routed: PROCEED to EVALUATE (Align primary home)."
      ]
    },
    "evaluate": {
      "id": "evaluate",
      "label": "EVALUATE",
      "kind": "guided",
      "userMode": "align",
      "role": "primary",
      "summary": "Align primary home: artifact check and later asks (D-review, User-driven, reconcile); PWB routes; never CALL next.",
      "permission": "read",
      "substates": [
        "artifactCheck",
        "askLoop",
        "synthesize"
      ],
      "procedure": [
        "Land here after envision scope ask is answered and start/reuse has named the artifact, after RETURN_ALIGN (landing evaluate), and after establish returns via the ALIGN body edge.",
        "READ Digest, Goal, Decisions (unresolved D), Checklist, Work log residuals, Current work, and the kickoff prompt if any — from the plan artifact; `.pi/AGENTS.md` and `.pi/MEMORY.md` as needed.",
        "NEVER explore the codebase in evaluate; if facts are missing, route to Spec (next or PWB) rather than searching source.",
        "IF kickoff/review lists specific D ids: CALL ask ONLY to accept/change/defer those Ds — do not invent new scope questions.",
        "ELSE IF the User message explicitly requests clarification: CALL ask for that request only.",
        "ELSE IF RECONCILE_SCOPE needs User keep/defer/replace/resolve options: CALL ask for that only.",
        "ELSE IF no User answers are required: do NOT CALL ask; summarize briefly and PROCEED to ESTABLISH, which CALLs next (never wait in editor without ask or next).",
        "NEVER re-fish entry goal-scope questions already captured in envision; NEVER invent fishing questions on entry.",
        "ASK dependent follow-ups in a later CALL only when still required after answers (ASK_LOOP stays in EVALUATE).",
        "APPEND every completed prompt, context, displayed option, confidence, and exact answer to User transcript.",
        "SYNTHESIZE into Goal, Align, Decisions, and Checklist after answers.",
        "IF Ask routes directly to SPEC or VIBE THEN proceed to EXPLORE or EXECUTE.",
        "On ask cancel: RETURN without calling next.",
        "NEVER CALL next from evaluate — when ready to leave Align or confirm routing, PROCEED to ESTABLISH."
      ]
    },
    "establish": {
      "id": "establish",
      "label": "ESTABLISH",
      "kind": "guided",
      "userMode": "align",
      "role": "secondary",
      "summary": "Align secondary gate: confirm/summarize, then RETURN to evaluate or CALL next/handoff — never ask.",
      "permission": "read",
      "substates": [
        "gateCheck",
        "routeNext"
      ],
      "procedure": [
        "Land here after next Align idle (NEXT_ALIGN, landing establish, no auto-start) and after evaluate proceeds on the ALIGN body edge.",
        "NEVER CALL ask from establish — entry scope ask is envision; other Align asks run in evaluate.",
        "No research in establish — confirm/summarize and route only.",
        "IF more Align primary or ask work remains THEN RETURN to EVALUATE.",
        "ELSE CALL next with ranked other modes and handoff only — NEVER include align. Agent-driven establish never idles without next.",
        "Idle landing (runtime NEXT_ALIGN, no agent turn): wait for User message or /mode; do not invent ask or next."
      ]
    },
    "explore": {
      "id": "explore",
      "label": "EXPLORE",
      "kind": "guided",
      "userMode": "spec",
      "role": "primary",
      "summary": "Spec primary home: codebase research and fact-finding; update the plan only — no project file mutations.",
      "permission": "read",
      "substates": [
        "symbolSearch",
        "evidenceGathering"
      ],
      "procedure": [
        "Land here after next→Spec, ask-route→Spec, and after elaborate returns for more research.",
        "BEGIN with one bounded exact symbol or path search.",
        "BROADEN only for a named unresolved reason and STOP when evidence answers it.",
        "EXCLUDE node_modules, generated, vendor, cache trees, and source maps unless explicitly targeted.",
        "RECORD findings in Evidence section; DO NOT mutate files outside .pi.",
        "FOR material autonomous choices RUN RECORD_DECISION (decide) while researching when needed (DECIDE_LOOP stays in EXPLORE).",
        "NEVER CALL next from explore — WHEN ready to propose or route, PROCEED to ELABORATE."
      ]
    },
    "elaborate": {
      "id": "elaborate",
      "label": "ELABORATE",
      "kind": "guided",
      "userMode": "spec",
      "role": "secondary",
      "summary": "Spec secondary gate: confirm/summarize, CLOSE_OUT, RETURN to explore or CALL next (not Spec).",
      "permission": "read",
      "substates": [
        "draftProposal",
        "checklistSynthesis",
        "closeOut"
      ],
      "procedure": [
        "EDIT Proposal and Checklist with the recommended approach.",
        "FOR EACH material autonomous choice RUN RECORD_DECISION(choice).",
        "RUN CLOSE_OUT.",
        "IF more research is required THEN RETURN to EXPLORE (do not CALL next with spec).",
        "ELSE CALL next with other modes only (never spec); prefer Align when D review is open; include handoff when useful.",
        "RETURN a concise proposal summary with artifact path."
      ]
    },
    "execute": {
      "id": "execute",
      "label": "EXECUTE",
      "kind": "guided",
      "userMode": "vibe",
      "role": "primary",
      "summary": "Vibe primary home: implement approved scope; scoped autonomous decisions (D); project file mutations.",
      "permission": "write",
      "substates": [
        "codeMutation",
        "recordDecision"
      ],
      "procedure": [
        "Land here after next→Vibe, ask-route→Vibe, and after examine returns for more implementation.",
        "IMPLEMENT accepted scope in project files outside .pi.",
        "FOR EACH material autonomous choice RUN RECORD_DECISION(choice) (DECIDE_LOOP stays in EXECUTE).",
        "UPDATE cumulative Checklist and append-only Work log throughout implementation.",
        "NEVER CALL next from execute — WHEN ready to verify or route, PROCEED to EXAMINE."
      ]
    },
    "examine": {
      "id": "examine",
      "label": "EXAMINE",
      "kind": "guided",
      "userMode": "vibe",
      "role": "secondary",
      "summary": "Vibe secondary gate: confirm/summarize, CLOSE_OUT, RETURN to execute or CALL next (not Vibe).",
      "permission": "write",
      "substates": [
        "runChecks",
        "recordEvidence",
        "closeOut"
      ],
      "procedure": [
        "RUN the smallest appropriate repository checks, then broader retained checks when risk warrants.",
        "IF a check fails within scope THEN RETURN to EXECUTE to fix and continue; ELSE RUN BLOCKED(failure) and prefer next→Align.",
        "RECORD check evidence in Work log.",
        "RUN CLOSE_OUT.",
        "IF more implementation remains THEN RETURN to EXECUTE (do not CALL next with vibe).",
        "ELSE CALL next with other modes only (never vibe); prefer Align when D review or acceptance is needed; include handoff when useful."
      ]
    }
  },
  "transitions": [
    {
      "id": "envision-ask-route-spec",
      "from": "envision",
      "event": "PWB_SPEC",
      "to": "explore",
      "label": "PWB → EXPLORE",
      "description": "Proceed-with-best from envision scope ask routes to SPEC primary (skips evaluate).",
      "userMediated": true
    },
    {
      "id": "envision-ask-route-vibe",
      "from": "envision",
      "event": "PWB_VIBE",
      "to": "execute",
      "label": "PWB → EXECUTE",
      "description": "Proceed-with-best from envision scope ask routes to VIBE primary (skips evaluate).",
      "userMediated": true
    },
    {
      "id": "envision-to-evaluate",
      "from": "envision",
      "event": "ARTIFACT",
      "to": "evaluate",
      "label": "ARTIFACT → EVALUATE",
      "description": "The envision ask was answered and start/reuse has named the artifact; enter Align primary home."
    },
    {
      "id": "evaluate-ask-loop",
      "from": "evaluate",
      "event": "ASK_LOOP",
      "to": "evaluate",
      "label": "Ask follow-up",
      "description": "Dependent follow-up questions stay in EVALUATE until answers are captured or ask routes away."
    },
    {
      "id": "evaluate-ask-route-spec",
      "from": "evaluate",
      "event": "PWB_SPEC",
      "to": "explore",
      "label": "PWB → EXPLORE",
      "description": "Proceed-with-best from evaluate ask routes to SPEC primary.",
      "userMediated": true
    },
    {
      "id": "evaluate-ask-route-vibe",
      "from": "evaluate",
      "event": "PWB_VIBE",
      "to": "execute",
      "label": "PWB → EXECUTE",
      "description": "Proceed-with-best from evaluate ask routes to VIBE primary.",
      "userMediated": true
    },
    {
      "id": "align-body",
      "from": "evaluate",
      "event": "ALIGN",
      "to": "establish",
      "label": "ALIGN",
      "description": "Align body: evaluate ASK_LOOP stays on the primary; establish only confirms/summarizes then RETURN to evaluate or CALL next.",
      "bidirectional": true
    },
    {
      "id": "establish-next-spec",
      "from": "establish",
      "event": "NEXT_SPEC",
      "to": "explore",
      "label": "next → EXPLORE",
      "description": "User chooses SPEC from establish gate; lands on explore (primary). next never includes align.",
      "userMediated": true
    },
    {
      "id": "establish-next-vibe",
      "from": "establish",
      "event": "NEXT_VIBE",
      "to": "execute",
      "label": "next → EXECUTE",
      "description": "User chooses VIBE from establish gate; lands on execute (primary).",
      "userMediated": true
    },
    {
      "id": "establish-handoff",
      "from": "establish",
      "event": "NEXT_HANDOFF",
      "to": "envision",
      "label": "next → handoff (new session ENVISION)",
      "description": "Picker prepares /handoff; after the User runs it, a fresh session restarts at ENVISION on the same artifact.",
      "userMediated": true
    },
    {
      "id": "explore-decide-loop",
      "from": "explore",
      "event": "DECIDE_LOOP",
      "to": "explore",
      "label": "Decide follow-up",
      "description": "Material autonomous choices stay in EXPLORE via decide until ready to propose."
    },
    {
      "id": "spec-body",
      "from": "explore",
      "event": "SPEC",
      "to": "elaborate",
      "label": "SPEC",
      "description": "Spec body: explore DECIDE_LOOP stays on the primary; elaborate only confirms/summarizes then RETURN to explore or CALL next.",
      "bidirectional": true
    },
    {
      "id": "elaborate-next-align",
      "from": "elaborate",
      "event": "NEXT_ALIGN",
      "to": "establish",
      "label": "next Align idle → ESTABLISH",
      "description": "Default Align after proposal: editor standby on establish gate; no auto-start ask.",
      "userMediated": true
    },
    {
      "id": "elaborate-return-align",
      "from": "elaborate",
      "event": "RETURN_ALIGN",
      "to": "evaluate",
      "label": "RETURN_ALIGN → EVALUATE",
      "description": "Align return when unresolved D ids are listed; auto-start evaluate ask for those Ds only.",
      "userMediated": true
    },
    {
      "id": "elaborate-next-vibe",
      "from": "elaborate",
      "event": "NEXT_VIBE",
      "to": "execute",
      "label": "CLOSE_OUT → next → EXECUTE",
      "description": "User chooses VIBE after proposal; lands on execute (primary). next never includes spec.",
      "userMediated": true
    },
    {
      "id": "elaborate-handoff",
      "from": "elaborate",
      "event": "NEXT_HANDOFF",
      "to": "envision",
      "label": "next → handoff (new session ENVISION)",
      "description": "Picker prepares /handoff from Spec gate; after the User runs it, a fresh session restarts at ENVISION on the same artifact.",
      "userMediated": true
    },
    {
      "id": "execute-decide-loop",
      "from": "execute",
      "event": "DECIDE_LOOP",
      "to": "execute",
      "label": "Decide follow-up",
      "description": "Material autonomous choices stay in EXECUTE via decide until ready to verify."
    },
    {
      "id": "vibe-body",
      "from": "execute",
      "event": "VIBE",
      "to": "examine",
      "label": "VIBE",
      "description": "Vibe body: execute DECIDE_LOOP stays on the primary; examine only confirms/summarizes then RETURN to execute or CALL next.",
      "bidirectional": true
    },
    {
      "id": "examine-next-align",
      "from": "examine",
      "event": "NEXT_ALIGN",
      "to": "establish",
      "label": "next Align idle → ESTABLISH",
      "description": "Default Align after verification: editor standby on establish gate; no auto-start ask.",
      "userMediated": true
    },
    {
      "id": "examine-return-align",
      "from": "examine",
      "event": "RETURN_ALIGN",
      "to": "evaluate",
      "label": "RETURN_ALIGN → EVALUATE",
      "description": "Align return when unresolved D ids are listed; auto-start evaluate ask for those Ds only.",
      "userMediated": true
    },
    {
      "id": "examine-next-spec",
      "from": "examine",
      "event": "NEXT_SPEC",
      "to": "explore",
      "label": "CLOSE_OUT → next → EXPLORE",
      "description": "User chooses SPEC after verification; lands on explore (primary). next never includes vibe.",
      "userMediated": true
    },
    {
      "id": "examine-handoff",
      "from": "examine",
      "event": "NEXT_HANDOFF",
      "to": "envision",
      "label": "next → handoff (new session ENVISION)",
      "description": "Picker prepares /handoff from Vibe gate; after the User runs it, a fresh session restarts at ENVISION on the same artifact.",
      "userMediated": true
    }
  ],
  "exceptions": {
    "title": "Manual Bypass & Escape Hatches",
    "summary": "The /mode command is the universal manual bypass. Running /mode opens the option picker at any time so the User can choose between ALIGN, SPEC, and VIBE (or hand off) without being gated by agent completion. next-driven pickers omit the current mode; /mode lists all 3 modes.",
    "commands": [
      {
        "command": "/mode",
        "label": "Open Mode Picker (Universal Bypass)",
        "summary": "Opens the mode option picker to choose any target mode (ALIGN, SPEC, VIBE) or hand off.",
        "description": "User-triggered escape hatch. Opens the interactive option picker in editor standby with the full mode list (ALIGN, SPEC, VIBE) so the User can switch mode, hand off, or return at any time."
      },
      {
        "command": "/handoff [name]",
        "label": "Direct Handoff Shortcut",
        "summary": "Swaps active session onto a named plan in fresh ALIGN.",
        "description": "Direct shortcut for session continuation on a named plan artifact, seeding a fresh ALIGN session at envision."
      }
    ],
    "rules": [
      "The /mode command is the canonical User-owned bypass to open the option picker and choose between ALIGN, SPEC, and VIBE.",
      "Manual bypass transitions are never gated on workflow completeness, pending recommendations, or unresolved D items.",
      "next-driven pickers never offer the current mode; ESC and Return to editor stay in the current mode without starting the agent. Show plan displays ## Digest and returns to the picker.",
      "Selecting an unrecommended mode in the /mode picker switches the session mode in editor standby.",
      "Direct /handoff swaps the plan file and seeds a fresh session in ALIGN (envision: artifact → scope ask → evaluate)."
    ]
  },
  "tools": [
    {
      "name": "start",
      "summary": "First .pi/plan write: named artifact after the first answered envision scope ask, or linked legacy continuation.",
      "modes": [
        "any"
      ],
      "gate": [
        "Creates or continues the named plan; no plan file exists until start succeeds."
      ],
      "mechanics": [
        "CALL start after the first envision scope ask is answered (not cancelled), or in the Spec/Vibe target before synthesize when PWB routed with no plan.",
        "CALL start with a scope-informed 2-4 word task name from settled scope plus the initial goal; include a ticket ID when applicable.",
        "Do not CALL start before that ask on a new session; do not create .pi/plan/* on cancel. When a named artifact already exists, reuse it and skip start.",
        "Legacy artifacts stay immutable; start forks a linked current-format continuation."
      ]
    },
    {
      "name": "ask",
      "summary": "Native ALIGN question loop; used from envision (entry scope; may precede start) and evaluate (later asks).",
      "modes": [
        "align"
      ],
      "gate": [
        "ALIGN-only; SPEC/VIBE ask is a harmless no-op (no picker).",
        "Empty ask is a harmless no-op.",
        "Non-empty ALIGN ask may run when no named plan exists (envision entry). Decide and next still require a named plan.",
        "Interactive UI required only when questions will be shown."
      ],
      "mechanics": [
        "Envision entry MAY CALL ask before start when no named artifact exists; evaluate asks require a named plan.",
        "CALL ask from envision once (one CALL; batch independent questions); do not CREATE .pi/plan/* until that ask is answered; persist User-transcript meaning after start; on answered (not routed) CALL start if needed then PROCEED to evaluate; on cancel RETURN without start. Do not CALL ask again from envision.",
        "CALL ask from evaluate for D acceptance, User-requested clarification, RECONCILE_SCOPE, and follow-ups — not to re-fish entry scope.",
        "Answers stay in ALIGN; after evaluate capture continue evaluate or PROCEED to establish for next/handoff; NEVER CALL next from envision or evaluate.",
        "CALL ask without sibling tools so cancellation or a direct SPEC/VIBE route can settle cleanly.",
        "KEEP question identifiers, option values, and option labels distinct. Question id is a Q-topic slug the User and Agent share. Option labels are short slugs; NEVER embed Q/D/C ids in labels.",
        "NEVER imitate native action labels.",
        "NEVER customize the Write a custom answer row label — it is always plain Write a custom answer; put User-supplied detail in question context or real options; NEVER offer a selectable option that merely says specify.",
        "BATCH only independent questions; dependent follow-ups in a later CALL from evaluate, not a second envision CALL.",
        "An optionless ask question offers custom input but no Proceed-with-best route.",
        "Proceed-with-best accepts prior answers plus remaining highest-confidence answers and starts fresh SPEC/VIBE at that mode's primary.",
        "On PWB route, runtime carries structured answers in the target kickoff; if no named artifact yet, the target CALL start first with a scope-informed name, then synthesizes User transcript / Goal / Align / Decisions / Checklist before other primary work (Align turn ends via terminate).",
        "Ask option order: selectable options, then Write a custom answer, then Proceed-with-best routes last.",
        "Agent persists User-transcript meaning; runtime does not write the User transcript."
      ]
    },
    {
      "name": "decide",
      "summary": "Agent autonomous decision logger; records rationale and unblocks execution without prompt.",
      "modes": [
        "spec",
        "vibe"
      ],
      "gate": [
        "SPEC/VIBE-only; ALIGN decide is a harmless no-op (no decision recorded).",
        "Empty decide is a harmless no-op.",
        "Optionless decide is a harmless no-op (compared options required).",
        "Non-empty decide with options requires a named session plan file; otherwise error."
      ],
      "mechanics": [
        "Never opens a picker and never changes mode.",
        "Auto-picks the highest-confidence option per question.",
        "Records agent-workflow:decision and appends under Agent transcript after start.",
        "Leaves D review unresolved until explicit ALIGN acceptance."
      ]
    },
    {
      "name": "next",
      "summary": "Queue ranked post-turn actions from a secondary gate; user chooses another mode or handoff (never the current mode).",
      "modes": [
        "any"
      ],
      "gate": [
        "Empty next records no recommendation and opens no picker.",
        "Non-empty next requires valid targets and a non-empty user-facing reason on every action; requires named session plan.",
        "Spec/Vibe actions need contextual prompt; Align evaluate/review needs a prompt with a standalone D-topic slug (D-tighten-writes); Align establish/idle prompt optional; handoff must omit prompt."
      ],
      "mechanics": [
        "CALL next only from secondary gates (establish, elaborate, examine) after capture/verify/CLOSE_OUT as appropriate.",
        "NEVER include an action whose mode equals the current persisted mode; runtime filters those out on next-driven pickers.",
        "Align dual landing: landing \"establish\" (default) ≡ graph NEXT_ALIGN → establish (editor standby, no auto-start); landing \"evaluate\" ≡ graph RETURN_ALIGN → evaluate (auto-start ask review — prompt MUST include a standalone D-topic slug: D-tighten-writes).",
        "Do not recommend Align landing establish idle after Spec/Vibe — static Return→ALIGN covers it; use landing evaluate only when unresolved D acceptance is required.",
        "When Align evaluate is recommended with other modes, list landing evaluate (RETURN_ALIGN) last among recommended rows (PWB-style separation).",
        "Agent-authored reason MUST be a short user-facing slug in plain English; plan slugs (Q-topic/C-topic/D-topic) only as optional trailing [] or (); never the whole reason. Runtime requires a non-empty normalized reason. Spec/Vibe REQUIRE prompt; Align evaluate REQUIRES a standalone D-topic slug (D-tighten-writes); handoff OMITs prompt.",
        "Runtime PREPENDS only Switch context when auto-starting and NEVER authors substantive direction.",
        "Recommended row with a reason shows {mode} — {reason}. Two Align rows may appear (review vs editor).",
        "next→Align idle lands establish; next→Align review lands evaluate; next→Spec lands explore; next→Vibe lands execute.",
        "ESC dismisses the mode picker with no change. Mode pickers end with Return to editor (same as ESC), then Return → ALIGN when not already in Align (static establish, no agent start), then Show plan (## Digest only; returns to the picker). /mode lists the same trailing rows.",
        "/mode force picker still lists all modes including the current mode (bypass).",
        "Manual ALIGN/SPEC/VIBE commands return to the editor without auto-start.",
        "Only recommended actions with autostart (prompt + non-idle Align) start the agent.",
        "Picker-selected handoff prepares /handoff for explicit User execution.",
        "Ask-routed SPEC/VIBE and /handoff still auto-start."
      ]
    }
  ],
  "artifact": {
    "sections": [
      "Digest",
      "Goal",
      "Align",
      "Decisions",
      "Evidence",
      "Proposal",
      "Checklist",
      "Work log",
      "User transcript",
      "Agent transcript"
    ],
    "identifiers": {
      "Q": "Stable immutable question slug (e.g. Q-goal-scope)",
      "D": "Stable immutable decision slug (e.g. D-tighten-writes)",
      "C": "Stable immutable checklist slug (e.g. C-diagnose-jobs)"
    },
    "rules": [
      "PRESERVE historical prose and APPEND lifecycle developments instead of rewriting history.",
      "KEEP Decisions as the concise accepted synthesis of User answers and reviewed Agent choices.",
      "INTERPRET status from the artifact as a whole.",
      "TREAT CLOSE_OUT as a procedure, not an artifact section."
    ]
  },
  "initial": "envision",
  "notes": [
    "Guided session story: envision (one ask call → start/reuse) → mode primary ⇄ secondary gate → next to another mode's primary; Handoff = fresh session at envision on the same artifact. Idle product UI is not a graph node.",
    "Persisted User mode is only align|spec|vibe. Guided states compose modeBodies with roles entry|primary|secondary. closeOut, blocked, and handoff are procedural helpers — not peer session modes.",
    "Project permission is read|write only (project-write boundary): read may update `.pi` plan state; write may change project files. All modes may edit the plan artifact. Align’s pre-ask rule (Agent, not a runtime sandbox): no extra file reads before the first scope ask (harness-injected AGENTS.md only); after that ask and start, the session plan then `.pi` as needed.",
    "Only secondary gates establish/elaborate/examine CALL next. envision CALL ask once for goal-scope (one CALL, batch independent questions; before start when no named artifact) then start/reuse then ARTIFACT→evaluate (or PWB); evaluate CALL later asks and PWB; establish never asks. Spec/Vibe→Align: NEXT_ALIGN→establish (idle editor), RETURN_ALIGN→evaluate (ask). next never recommends the current mode. NEXT_HANDOFF from establish, elaborate, and examine → envision (/handoff prep).",
    "session.scope and session.review are Agent-tracked meaning, not runtime-parsed fields.",
    "Transition table is the guided graph only. Stay-in-mode via mode-body edges (ALIGN/SPEC/VIBE), ESC, Return to editor, ask cancel, and /mode are not same-mode NEXT edges. Primaries self-loop: evaluate ASK_LOOP; explore and execute DECIDE_LOOP. Envision runs one ask CALL then start/reuse then ARTIFACT→evaluate (no ASK_LOOP). Secondaries only confirm/summarize then RETURN to the primary or CALL next. Manual /mode bypasses live under Exceptions.",
    "Substates on guided states are narrative procedure phases for agents and diagrams, not separate graph nodes.",
    "Preferred agent path ends SPEC/VIBE via CLOSE_OUT on the secondary before CALL next. Agent-driven Align ends via ask (envision/evaluate) or next (establish); silent idle is only runtime NEXT_ALIGN.",
    "Counts, confidence, uniqueness, concise text, identifiers, and naming quality are Agent responsibilities.",
    "IF a tool call is rejected THEN CORRECT it, RETRY once, and NEVER claim the rejected action succeeded.",
    "tools validate required shapes and protocol enums, not workflow quality."
  ]
};
